package Exceptions;

import java.io.IOException;

public class tryCtchblock {
	public void m1() throws Exception
	{
		throw new ArithmeticException();
	}
	public void m2() {
		try
		{
		m1();
		}
		catch(Exception e)
		{
			
		}
	}
	public static void main(String args[])
	{
		
	}
}
